FROM wuhanchu/text2vec_service:1.3.8


# RUN groupadd -r mygroup && useradd --no-log-init -r -g mygroup myuser
# USER myuser
WORKDIR /opt/service/
COPY "./" "./"
USER root
RUN chmod +x ./run.sh 
RUN pip3 install -r ./requirements.txt  -i https://pypi.doubanio.com/simple --extra-index-url  https://pypi.org/simple/ 

