FROM wuhanchu/text2vec_service:latest


RUN groupadd -r mygroup && useradd --no-log-init -r -g mygroup myuser
USER myuser

# WORKDIR /opt/service/

# RUN groupadd -r mygroup && useradd --no-log-init -r -g mygroup myuser
# USER myuser


# COPY "./" "./"
# RUN pip3 install -r ./requirements.txt  -i https://pypi.doubanio.com/simple --extra-index-url  https://pypi.org/simple/ 

# RUN chmod +x ./run.sh