FROM wuhanchu/text2vec_service
WORKDIR /opt/service/

COPY "./" "./"
RUN pip3 install -r ./requirements.txt  -i https://pypi.doubanio.com/simple --extra-index-url  https://pypi.org/simple/ 

RUN chmod +x ./run.sh